Botón añadido al nav para abrir y cerrar el menú
SalamandraDevs/salamandradevs.site pull request #24
Opened 2023-04-09 17:26 UTC by VladImpaler64

Añadí el botón, para la versión mobile, a la <ul> del <nav> para no alterar los otros elementos (su disposición) la idea es que con JS el componente del menú se abra y muestre la lista de artículos, el modo nocturno y otra cosa que tengan pensada, todo dentro de un div, con un diseño transparente. Esa sería la próxima tarea, definir lo que irá en ese menú de navegación y quizás fusionar los otros links para que quede más limpio.

2023-04-12 15:16 UTC, SalamandraDevs commented on themes/droda/assets/css/main.css
> +.boton-movil {
Debemos usar nombres de clases en inglés y de hecho evitar el uso de nombres de clases si es posible, esto se hace con selectores CSS que para el caso del navbar si te fijas son solo usar algo así:

```css
nav button {
   ....
}
```

Sería suficiente dado que intentamos que el sitio sea full semántico, es más si ves algo no semántico por ahí nos lo comentas. Aquí el código del nav con el botón que deberías añadir.

```html
{{ "<!-- Partial block for navbar -->" | safeHTML }}
<nav>
  {{ with .Site.GetPage "home" }}
  <div><img src="{{ .Params.homeIcon | absURL }}" alt=""><a class="hover" href="{{ .Permalink }}">{{ .Title }}</a></div>
  {{ end }}
  <ul>
  {{ range .Site.Sections }}
  <li><a class="hover" href="{{ .Permalink }}">{{ .Title }}</a></li>
  {{ end }}
  </ul>
  <button></button>
</nav>
```

Dado que `<nav>`  es un elemento flex con space-between quedaría bien.

2023-04-12 15:17 UTC, SalamandraDevs commented on themes/droda/assets/css/main.css
> +      display: none;
Replanteemos un poco el uso del botón.

Inicialmente pensábamos que sirviera para mostrar y ocultar el `<aside>`, pero yo pienso que es mejor que este botón aparezca en tamaños pequeños así como lo has definido, pero para mostrar las entradas de menú que hay al lado derecho, es decir, en móviles oculatamos las entradas de menú del lado derecho del `<nav>` y las motramos y oculatamos con el botón de hamburguesa en el `<aside>`.

Dichas entradas que hoy son "blog" y "acerca de", quedarían entonces en el aside, por lo que sólo sería copiar esa parte del código que está hoy en `<nav>` para dentro de `<aside>`. Más adelante tendremos más entradas, por lo que será útil. De hecho, una función que tendrá ese aside, será mostrar la tabla de contenidos de los artículos del blog, más adelante alguien se encargará.

2023-04-12 15:17 UTC, SalamandraDevs commented on themes/droda/layouts/partials/boton.html
> +<button class="boton-movil" data-visible="false" onclick="
Todo este código debería ir en el JS del sitio que está dentro del directorio assets del tema.

Sería algo tal que así:

```javascript
const hammButton = document.querySelector("nav button");
...
...
```

Como notarás no se hizo uso de clases sino de selectores, manteniendo más limpio el código y conservando la semántica.

2023-04-12 15:25 UTC, SalamandraDevs commented on themes/droda/layouts/partials/navbar.html
> +  {{ partial "boton.html" . }}
Ya arriba viste que no merece un {{ partial }} para esto.

2023-04-17 20:57 UTC, SalamandraDevs requested changes
Hola, te dejé dos observaciones respecto del uso de nombres de clases que deberían usarse sólo en casos donde resulte más complejo evadiar su uso.

También te pido ajustar un detalle que otro dev había hecho sobre los elementos a con hover en los menues, ese efecto de la barrita que aparece.

2023-04-17 20:57 UTC, SalamandraDevs commented on themes/droda/assets/css/main.css
>  aside .item {
Como te venía comentando, estamos evitando el uso de nombres de clases para que no se rompa la semántica html, favor deja así estos selectores:
```css
aside > div, li {
   color: var(--bgColorLight);
   display: flex;
   flex-flow: column nowrap;
   align-items: center;
   justify-content: space-between;
   font-size: 1.5rem;
   width: 100%;
   padding: 1rem 0;
}
```

2023-04-17 20:57 UTC, SalamandraDevs commented on themes/droda/layouts/partials/aside.html
> +    <li class="item"><a class="hover" href="{{ .Permalink }}">{{ .Title }}</a></li>
Quitar class="item" para los `div` hijos de `aside` y para los `li` hijos de `aside`. También revisa si le puedes quitar la clase `hover` a los elemenos que están dentro de los `li` y hacer lo mismo que hice yo con los selectores en el CSS. Si lo ves complicado déjalo así por ahora.

2023-04-17 21:03 UTC, VladImpaler64 commented on themes/droda/layouts/partials/aside.html
> +    <li class="item"><a class="hover" href="{{ .Permalink }}">{{ .Title }}</a></li>
Ah, eso estaba desde antes jaja alguien más lo hizo supongo

2023-04-17 21:59 UTC, SalamandraDevs commented on themes/droda/layouts/partials/aside.html
> +    <li class="item"><a class="hover" href="{{ .Permalink }}">{{ .Title }}</a></li>
Listo, yo lo arreglo.

2023-04-17 21:59 UTC, SalamandraDevs approved these changes

2023-04-17 21:59 UTC, merged